import { hashSync } from 'bcryptjs';

const users = [
  {
    id: '410544b2-4001-4271-9855-fec4b6a6442a',
    name: 'User',
    email: 'user@nextmail.com',
    password: hashSync('123456', 10),
  },
];

const alloys = [
  { code: 'AA', description: 'RENE-108' },
  { code: 'AB', description: 'DS-200HF' },
  { code: 'AS', description: 'N500' },
  { code: 'AV', description: 'RENE-125AV' },
  { code: 'BB', description: 'C-1023' },
  { code: 'BL', description: 'RENE-80' },
  { code: 'BV', description: 'DS-200HFAV' },
  { code: 'BX', description: 'RENE-77' },
  { code: 'BZ', description: 'C263' },
  { code: 'CJ', description: 'MAR-M-509' },
  { code: 'CK', description: 'CMSX-6' },
  { code: 'CM', description: 'CM-247LC' },
  { code: 'CS', description: 'INCO-713LC' },
  { code: 'CV', description: 'CMSX-3' },
  { code: 'CZ', description: 'X-40' },
  { code: 'DE', description: 'PWA-663' },
  { code: 'EF', description: 'GTD-444' },
  { code: 'EG', description: 'GTD-444M' },
  { code: 'FA', description: 'PWA-1455' },
  { code: 'FM', description: 'INCO-100' },
  { code: 'HN', description: 'INCO-738' },
  { code: 'JF', description: 'MAR-M-002' },
  { code: 'JT', description: 'U-500' },
  { code: 'KW', description: 'WASPALLOY' },
  { code: 'LE', description: 'LEK-94' },
  { code: 'LG', description: 'MAR-M-247' },
  { code: 'LV', description: 'C-101' },
  { code: 'MA', description: 'GTD-141' },
  { code: 'MD', description: 'MGA 1400DS' },
  { code: 'MG', description: 'GTD-111M' },
  { code: 'MZ', description: 'PWA-1422HF' },
  { code: 'PA', description: 'PWA-1432' },
  { code: 'PB', description: 'SIEMET' },
  { code: 'PD', description: 'PWA-1480' },
  { code: 'PE', description: 'ECY-768' },
  { code: 'PG', description: 'INCO-625' },
  { code: 'PH', description: 'PWA-1440' },
  { code: 'PJ', description: 'RENE-125' },
  { code: 'PK', description: 'CX-102' },
  { code: 'PL', description: 'INCO-939' },
  { code: 'PN', description: 'PWA-1483 / IN792SX' },
  { code: 'PT', description: 'INCO-792 MOD 5A' },
  { code: 'PZ', description: 'MAR-M-247LC' },
  { code: 'RA', description: 'MK-4LC' },
  { code: 'RC', description: 'MK-4HC' },
  { code: 'RD', description: 'RENE-142' },
  { code: 'RE', description: 'RENE-N5' },
  { code: 'RF', description: 'PWA-1484' },
  { code: 'RG', description: 'PWA-1426' },
  { code: 'RH', description: 'PWA-1487' },
  { code: 'RJ', description: 'RENE-N6' },
  { code: 'RK', description: 'CMSX-4' },
  { code: 'RL', description: 'CM-186LC' },
  { code: 'RN', description: 'RENE-N2' },
  { code: 'RS', description: 'RENE-N5LS' },
  { code: 'RT', description: 'RENE N515' },
  { code: 'RU', description: 'PWA 1429' },
  { code: 'SB', description: 'RENE-80H' },
  { code: 'SE', description: 'SEL' },
  { code: 'SR', description: 'SC-180' },
  { code: 'TA', description: 'INCO-713CMG' },
  { code: 'TB', description: 'RENE-108MG' },
  { code: 'TG', description: 'MAR-M-247MG' },
  { code: 'TH', description: 'INCO-738LCMG' },
  { code: 'TJ', description: 'C-101MG' },
  { code: 'TL', description: 'GTD-141MG' },
  { code: 'TM', description: 'CM-247LCMG' },
  { code: 'TO', description: 'GTD-111MG' },
  { code: 'TP', description: 'RENE-125MG' },
  { code: 'TR', description: 'RENE-125AVMG' },
  { code: 'TV', description: 'INCO-738LCMG' },
  { code: 'VA', description: 'GTD-741' },
  { code: 'VE', description: 'RENE-N411' },
  { code: 'VF', description: 'RENE-220' },
  { code: 'VS', description: 'RENE 411LS' },
  { code: 'VT', description: 'INCO-738LC' },
  { code: 'WR', description: 'PWA1430' },
];

const alloyChemistries = [
  { alloyCode: 'AA', element: 'C', value: 0.095 },
  { alloyCode: 'AA', element: 'CR', value: 8.4 },
  { alloyCode: 'AA', element: 'MO', value: 0.5 },
  { alloyCode: 'AA', element: 'TI', value: 0.75 },
  { alloyCode: 'AA', element: 'AL', value: 5.5 },
  { alloyCode: 'AA', element: 'CO', value: 9.5 },
  { alloyCode: 'AA', element: 'W', value: 9.5 },
  { alloyCode: 'AA', element: 'ZR', value: 0.015 },
  { alloyCode: 'AA', element: 'B', value: 0.015 },
  { alloyCode: 'AA', element: 'TA', value: 3.0 },
  { alloyCode: 'AA', element: 'HF', value: 1.6 },
  { alloyCode: 'AA', element: 'NI', value: 61.1 },
  { alloyCode: 'AB', element: 'C', value: 0.13 },
  { alloyCode: 'AB', element: 'CR', value: 8.5 },
  { alloyCode: 'AB', element: 'TI', value: 1.9 },
  { alloyCode: 'AB', element: 'AL', value: 4.85 },
  { alloyCode: 'AB', element: 'CO', value: 9.45 },
  { alloyCode: 'AB', element: 'W', value: 11.7 },
  { alloyCode: 'AB', element: 'B', value: 0.015 },
  { alloyCode: 'AB', element: 'CB', value: 1.0 },
  { alloyCode: 'AB', element: 'HF', value: 1.95 },
  { alloyCode: 'AB', element: 'NI', value: 60.5 },
  { alloyCode: 'AS', element: 'C', value: 0.035 },
  { alloyCode: 'AS', element: 'CR', value: 6.0 },
  { alloyCode: 'AS', element: 'MO', value: 1.5 },
  { alloyCode: 'AS', element: 'AL', value: 6.5 },
  { alloyCode: 'AS', element: 'CO', value: 7.5 },
  { alloyCode: 'AS', element: 'W', value: 6.25 },
  { alloyCode: 'AS', element: 'B', value: 0.004 },
  { alloyCode: 'AS', element: 'TA', value: 6.6 },
  { alloyCode: 'AS', element: 'HF', value: 0.15 },
  { alloyCode: 'AS', element: 'NI', value: 65.5 },
  { alloyCode: 'AV', element: 'C', value: 0.12 },
  { alloyCode: 'AV', element: 'CR', value: 8.9 },
  { alloyCode: 'AV', element: 'MO', value: 1.8 },
  { alloyCode: 'AV', element: 'TI', value: 2.5 },
  { alloyCode: 'AV', element: 'AL', value: 4.75 },
  { alloyCode: 'AV', element: 'CO', value: 9.8 },
  { alloyCode: 'AV', element: 'W', value: 6.8 },
  { alloyCode: 'AV', element: 'ZR', value: 0.035 },
  { alloyCode: 'AV', element: 'B', value: 0.015 },
  { alloyCode: 'AV', element: 'TA', value: 3.8 },
  { alloyCode: 'AV', element: 'HF', value: 1.55 },
  { alloyCode: 'AV', element: 'NI', value: 59.9 },
  { alloyCode: 'BB', element: 'C', value: 0.15 },
  { alloyCode: 'BB', element: 'CR', value: 15.5 },
  { alloyCode: 'BB', element: 'MO', value: 8.3 },
  { alloyCode: 'BB', element: 'TI', value: 4.0 },
  { alloyCode: 'BB', element: 'AL', value: 4.5 },
  { alloyCode: 'BB', element: 'CO', value: 10.0 },
  { alloyCode: 'BB', element: 'NI', value: 57.5 },
  { alloyCode: 'BL', element: 'C', value: 0.17 },
  { alloyCode: 'BL', element: 'CR', value: 14.1 },
  { alloyCode: 'BL', element: 'MO', value: 4.0 },
  { alloyCode: 'BL', element: 'TI', value: 5.0 },
  { alloyCode: 'BL', element: 'AL', value: 2.9 },
  { alloyCode: 'BL', element: 'CO', value: 9.5 },
  { alloyCode: 'BL', element: 'W', value: 4.0 },
  { alloyCode: 'BL', element: 'ZR', value: 0.025 },
  { alloyCode: 'BL', element: 'B', value: 0.015 },
  { alloyCode: 'BL', element: 'NI', value: 60.3 },

  { alloyCode: 'BV', element: 'C', value: 0.13 },
  { alloyCode: 'BV', element: 'CR', value: 8.5 },
  { alloyCode: 'BV', element: 'TI', value: 1.9 },
  { alloyCode: 'BV', element: 'AL', value: 4.85 },
  { alloyCode: 'BV', element: 'CO', value: 9.45 },
  { alloyCode: 'BV', element: 'W', value: 11.7 },
  { alloyCode: 'BV', element: 'B', value: 0.015 },
  { alloyCode: 'BV', element: 'CB', value: 1.0 },
  { alloyCode: 'BV', element: 'HF', value: 1.95 },
  { alloyCode: 'BV', element: 'NI', value: 60.5 },

  { alloyCode: 'BX', element: 'C', value: 0.07 },
  { alloyCode: 'BX', element: 'CR', value: 14.4 },
  { alloyCode: 'BX', element: 'MO', value: 4.1 },
  { alloyCode: 'BX', element: 'TI', value: 3.5 },
  { alloyCode: 'BX', element: 'AL', value: 4.5 },
  { alloyCode: 'BX', element: 'CO', value: 14.5 },
  { alloyCode: 'BX', element: 'B', value: 0.016 },
  { alloyCode: 'BX', element: 'NI', value: 58.9 },
  { alloyCode: 'BZ', element: 'C', value: 0.06 },
  { alloyCode: 'BZ', element: 'CR', value: 20.0 },
  { alloyCode: 'BZ', element: 'MO', value: 5.85 },
  { alloyCode: 'BZ', element: 'TI', value: 2.15 },
  { alloyCode: 'BZ', element: 'AL', value: 0.45 },
  { alloyCode: 'BZ', element: 'CO', value: 20.0 },
  { alloyCode: 'BZ', element: 'NI', value: 51.5 },
  { alloyCode: 'CJ', element: 'C', value: 0.6 },
  { alloyCode: 'CJ', element: 'CR', value: 23.5 },
  { alloyCode: 'CJ', element: 'TI', value: 0.23 },
  { alloyCode: 'CJ', element: 'CO', value: 54.45 },
  { alloyCode: 'CJ', element: 'W', value: 7.1 },
  { alloyCode: 'CJ', element: 'ZR', value: 0.42 },
  { alloyCode: 'CJ', element: 'TA', value: 3.5 },
  { alloyCode: 'CJ', element: 'NI', value: 10.2 },
  { alloyCode: 'CK', element: 'CR', value: 10.0 },
  { alloyCode: 'CK', element: 'MO', value: 3.0 },
  { alloyCode: 'CK', element: 'TI', value: 4.7 },
  { alloyCode: 'CK', element: 'AL', value: 4.8 },
  { alloyCode: 'CK', element: 'CO', value: 5.0 },
  { alloyCode: 'CK', element: 'TA', value: 2.0 },
  { alloyCode: 'CK', element: 'HF', value: 0.07 },
  { alloyCode: 'CK', element: 'NI', value: 70.4 },
  { alloyCode: 'CM', element: 'C', value: 0.075 },
  { alloyCode: 'CM', element: 'CR', value: 8.15 },
  { alloyCode: 'CM', element: 'MO', value: 0.53 },
  { alloyCode: 'CM', element: 'TI', value: 0.73 },
  { alloyCode: 'CM', element: 'AL', value: 5.6 },
  { alloyCode: 'CM', element: 'CO', value: 9.35 },
  { alloyCode: 'CM', element: 'W', value: 9.45 },
  { alloyCode: 'CM', element: 'ZR', value: 0.01 },
  { alloyCode: 'CM', element: 'B', value: 0.016 },
  { alloyCode: 'CM', element: 'TA', value: 3.23 },
  { alloyCode: 'CM', element: 'HF', value: 1.5 },
  { alloyCode: 'CM', element: 'NI', value: 61.4 },
  { alloyCode: 'CS', element: 'C', value: 0.06 },
  { alloyCode: 'CS', element: 'CR', value: 11.75 },
  { alloyCode: 'CS', element: 'MO', value: 4.3 },
  { alloyCode: 'CS', element: 'TI', value: 0.6 },
  { alloyCode: 'CS', element: 'AL', value: 6.1 },
  { alloyCode: 'CS', element: 'ZR', value: 0.055 },
  { alloyCode: 'CS', element: 'B', value: 0.01 },
  { alloyCode: 'CS', element: 'CB', value: 2.0 },
  { alloyCode: 'CS', element: 'NI', value: 75.1 },
  { alloyCode: 'CV', element: 'CR', value: 7.8 },
  { alloyCode: 'CV', element: 'MO', value: 0.5 },
  { alloyCode: 'CV', element: 'TI', value: 1.0 },
  { alloyCode: 'CV', element: 'AL', value: 5.64 },
  { alloyCode: 'CV', element: 'CO', value: 4.6 },
  { alloyCode: 'CV', element: 'W', value: 8.0 },
  { alloyCode: 'CV', element: 'TA', value: 6.0 },
  { alloyCode: 'CV', element: 'HF', value: 0.09 },
  { alloyCode: 'CV', element: 'NI', value: 66.4 },
  { alloyCode: 'CZ', element: 'C', value: 0.5 },
  { alloyCode: 'CZ', element: 'SI', value: 0.8 },
  { alloyCode: 'CZ', element: 'MN', value: 0.65 },
  { alloyCode: 'CZ', element: 'CR', value: 25.6 },
  { alloyCode: 'CZ', element: 'AL', value: 0.3 },
  { alloyCode: 'CZ', element: 'CO', value: 54.4 },
  { alloyCode: 'CZ', element: 'W', value: 7.5 },
  { alloyCode: 'DE', element: 'CR', value: 8.3 },
  { alloyCode: 'DE', element: 'MO', value: 6.1 },
  { alloyCode: 'DE', element: 'TI', value: 0.95 },
  { alloyCode: 'DE', element: 'AL', value: 6.0 },
  { alloyCode: 'DE', element: 'CO', value: 10.0 },
  { alloyCode: 'DE', element: 'ZR', value: 0.06 },
  { alloyCode: 'DE', element: 'B', value: 0.015 },
  { alloyCode: 'DE', element: 'TA', value: 4.15 },
  { alloyCode: 'DE', element: 'NI', value: 64.3 },
  { alloyCode: 'EF', element: 'C', value: 0.08 },
  { alloyCode: 'EF', element: 'CR', value: 9.65 },
  { alloyCode: 'EF', element: 'MO', value: 1.44 },
  { alloyCode: 'EF', element: 'TI', value: 3.45 },
  { alloyCode: 'EF', element: 'AL', value: 4.15 },
  { alloyCode: 'EF', element: 'CO', value: 7.5 },
  { alloyCode: 'EF', element: 'W', value: 6.0 },
  { alloyCode: 'EF', element: 'B', value: 0.0088 },
  { alloyCode: 'EF', element: 'CB', value: 0.5 },
  { alloyCode: 'EF', element: 'TA', value: 4.75 },
  { alloyCode: 'EF', element: 'HF', value: 0.13 },
  { alloyCode: 'EF', element: 'NI', value: 62.3 },
  { alloyCode: 'EG', element: 'C', value: 0.095 },
  { alloyCode: 'EG', element: 'CR', value: 9.65 },
  { alloyCode: 'EG', element: 'MO', value: 1.44 },
  { alloyCode: 'EG', element: 'TI', value: 3.68 },
  { alloyCode: 'EG', element: 'AL', value: 4.2 },
  { alloyCode: 'EG', element: 'CO', value: 7.5 },
  { alloyCode: 'EG', element: 'W', value: 6.0 },
  { alloyCode: 'EG', element: 'B', value: 0.01 },
  { alloyCode: 'EG', element: 'CB', value: 0.5 },
  { alloyCode: 'EG', element: 'TA', value: 4.75 },
  { alloyCode: 'EG', element: 'HF', value: 0.06 },
  { alloyCode: 'EG', element: 'NI', value: 62.1 },
  { alloyCode: 'FA', element: 'C', value: 0.12 },
  { alloyCode: 'FA', element: 'CR', value: 8.0 },
  { alloyCode: 'FA', element: 'MO', value: 6.0 },
  { alloyCode: 'FA', element: 'TI', value: 0.85 },
  { alloyCode: 'FA', element: 'AL', value: 6.0 },
  { alloyCode: 'FA', element: 'CO', value: 10.0 },
  { alloyCode: 'FA', element: 'ZR', value: 0.03 },
  { alloyCode: 'FA', element: 'B', value: 0.015 },
  { alloyCode: 'FA', element: 'TA', value: 4.25 },
  { alloyCode: 'FA', element: 'HF', value: 1.15 },
  { alloyCode: 'FA', element: 'NI', value: 63.6 },
  { alloyCode: 'FM', element: 'C', value: 0.18 },
  { alloyCode: 'FM', element: 'CR', value: 9.0 },
  { alloyCode: 'FM', element: 'MO', value: 3.0 },
  { alloyCode: 'FM', element: 'TI', value: 4.65 },
  { alloyCode: 'FM', element: 'AL', value: 5.55 },
  { alloyCode: 'FM', element: 'CO', value: 14.5 },
  { alloyCode: 'FM', element: 'V', value: 0.8 },
  { alloyCode: 'FM', element: 'ZR', value: 0.033 },
  { alloyCode: 'FM', element: 'B', value: 0.015 },
  { alloyCode: 'FM', element: 'TA', value: 0.0 },
  { alloyCode: 'FM', element: 'NI', value: 62.3 },
  { alloyCode: 'HN', element: 'C', value: 0.16 },
  { alloyCode: 'HN', element: 'CR', value: 16.0 },
  { alloyCode: 'HN', element: 'MO', value: 1.75 },
  { alloyCode: 'HN', element: 'TI', value: 3.4 },
  { alloyCode: 'HN', element: 'AL', value: 3.5 },
  { alloyCode: 'HN', element: 'CO', value: 8.5 },
  { alloyCode: 'HN', element: 'W', value: 2.6 },
  { alloyCode: 'HN', element: 'ZR', value: 0.07 },
  { alloyCode: 'HN', element: 'B', value: 0.01 },
  { alloyCode: 'HN', element: 'CB', value: 0.85 },
  { alloyCode: 'HN', element: 'TA', value: 1.8 },
  { alloyCode: 'HN', element: 'NI', value: 61.4 },
  { alloyCode: 'JF', element: 'C', value: 0.15 },
  { alloyCode: 'JF', element: 'CR', value: 9.0 },
  { alloyCode: 'JF', element: 'TI', value: 1.5 },
  { alloyCode: 'JF', element: 'AL', value: 5.5 },
  { alloyCode: 'JF', element: 'CO', value: 10.0 },
  { alloyCode: 'JF', element: 'W', value: 10.0 },
  { alloyCode: 'JF', element: 'ZR', value: 0.038 },
  { alloyCode: 'JF', element: 'B', value: 0.015 },
  { alloyCode: 'JF', element: 'TA', value: 2.5 },
  { alloyCode: 'JF', element: 'HF', value: 1.5 },
  { alloyCode: 'JF', element: 'NI', value: 59.8 },
  { alloyCode: 'JT', element: 'C', value: 0.065 },
  { alloyCode: 'JT', element: 'CR', value: 18.4 },
  { alloyCode: 'JT', element: 'MO', value: 4.0 },
  { alloyCode: 'JT', element: 'TI', value: 2.9 },
  { alloyCode: 'JT', element: 'AL', value: 2.85 },
  { alloyCode: 'JT', element: 'CO', value: 18.4 },
  { alloyCode: 'JT', element: 'B', value: 0.006 },
  { alloyCode: 'JT', element: 'NI', value: 53.4 },
  { alloyCode: 'KW', element: 'C', value: 0.07 },
  { alloyCode: 'KW', element: 'CR', value: 19.5 },
  { alloyCode: 'KW', element: 'MO', value: 4.3 },
  { alloyCode: 'KW', element: 'TI', value: 2.9 },
  { alloyCode: 'KW', element: 'AL', value: 1.3 },
  { alloyCode: 'KW', element: 'CO', value: 13.5 },
  { alloyCode: 'KW', element: 'ZR', value: 0.065 },
  { alloyCode: 'KW', element: 'B', value: 0.005 },
  { alloyCode: 'KW', element: 'NI', value: 58.4 },
  { alloyCode: 'LE', element: 'C', value: 0.02 },
  { alloyCode: 'LE', element: 'CR', value: 6.1 },
  { alloyCode: 'LE', element: 'MO', value: 2.0 },
  { alloyCode: 'LE', element: 'TI', value: 1.0 },
  { alloyCode: 'LE', element: 'AL', value: 6.5 },
  { alloyCode: 'LE', element: 'CO', value: 7.5 },
  { alloyCode: 'LE', element: 'W', value: 3.5 },
  { alloyCode: 'LE', element: 'TA', value: 2.3 },
  { alloyCode: 'LE', element: 'HF', value: 0.1 },
  { alloyCode: 'LE', element: 'RE', value: 2.45 },
  { alloyCode: 'LE', element: 'NI', value: 68.5 },
  { alloyCode: 'LG', element: 'C', value: 0.16 },
  { alloyCode: 'LG', element: 'CR', value: 8.25 },
  { alloyCode: 'LG', element: 'MO', value: 0.75 },
  { alloyCode: 'LG', element: 'TI', value: 1.0 },
  { alloyCode: 'LG', element: 'AL', value: 5.55 },
  { alloyCode: 'LG', element: 'CO', value: 9.9 },
  { alloyCode: 'LG', element: 'W', value: 10.05 },
  { alloyCode: 'LG', element: 'ZR', value: 0.032 },
  { alloyCode: 'LG', element: 'B', value: 0.015 },
  { alloyCode: 'LG', element: 'TA', value: 3.0 },
  { alloyCode: 'LG', element: 'HF', value: 1.5 },
  { alloyCode: 'LG', element: 'NI', value: 59.8 },
  { alloyCode: 'LV', element: 'C', value: 0.08 },
  { alloyCode: 'LV', element: 'CR', value: 12.7 },
  { alloyCode: 'LV', element: 'MO', value: 1.85 },
  { alloyCode: 'LV', element: 'TI', value: 4.1 },
  { alloyCode: 'LV', element: 'AL', value: 3.4 },
  { alloyCode: 'LV', element: 'CO', value: 8.9 },
  { alloyCode: 'LV', element: 'W', value: 4.1 },
  { alloyCode: 'LV', element: 'ZR', value: 0.033 },
  { alloyCode: 'LV', element: 'B', value: 0.015 },
  { alloyCode: 'LV', element: 'TA', value: 4.4 },
  { alloyCode: 'LV', element: 'HF', value: 0.95 },
  { alloyCode: 'LV', element: 'NI', value: 59.5 },
  { alloyCode: 'MA', element: 'C', value: 0.09 },
  { alloyCode: 'MA', element: 'CR', value: 14.0 },
  { alloyCode: 'MA', element: 'MO', value: 1.5 },
  { alloyCode: 'MA', element: 'TI', value: 4.9 },
  { alloyCode: 'MA', element: 'AL', value: 3.0 },
  { alloyCode: 'MA', element: 'CO', value: 9.35 },
  { alloyCode: 'MA', element: 'W', value: 3.8 },
  { alloyCode: 'MA', element: 'B', value: 0.012 },
  { alloyCode: 'MA', element: 'CB', value: 0.12 },
  { alloyCode: 'MA', element: 'TA', value: 2.55 },
  { alloyCode: 'MA', element: 'NI', value: 60.7 },
  { alloyCode: 'MD', element: 'C', value: 0.07 },
  { alloyCode: 'MD', element: 'CR', value: 13.25 },
  { alloyCode: 'MD', element: 'MO', value: 1.7 },
  { alloyCode: 'MD', element: 'TI', value: 2.4 },
  { alloyCode: 'MD', element: 'AL', value: 3.95 },
  { alloyCode: 'MD', element: 'CO', value: 10.0 },
  { alloyCode: 'MD', element: 'W', value: 4.6 },
  { alloyCode: 'MD', element: 'B', value: 0.017 },
  { alloyCode: 'MD', element: 'TA', value: 4.8 },
  { alloyCode: 'MD', element: 'NI', value: 59.2 },
  { alloyCode: 'MG', element: 'C', value: 0.09 },
  { alloyCode: 'MG', element: 'CR', value: 13.8 },
  { alloyCode: 'MG', element: 'MO', value: 1.5 },
  { alloyCode: 'MG', element: 'TI', value: 4.8 },
  { alloyCode: 'MG', element: 'AL', value: 2.9 },
  { alloyCode: 'MG', element: 'CO', value: 9.3 },
  { alloyCode: 'MG', element: 'W', value: 3.77 },
  { alloyCode: 'MG', element: 'B', value: 0.012 },
  { alloyCode: 'MG', element: 'TA', value: 2.75 },
  { alloyCode: 'MG', element: 'NI', value: 61.1 },
  { alloyCode: 'MZ', element: 'C', value: 0.15 },
  { alloyCode: 'MZ', element: 'CR', value: 8.5 },
  { alloyCode: 'MZ', element: 'TI', value: 1.9 },
  { alloyCode: 'MZ', element: 'AL', value: 4.85 },
  { alloyCode: 'MZ', element: 'CO', value: 9.6 },
  { alloyCode: 'MZ', element: 'W', value: 12.0 },
  { alloyCode: 'MZ', element: 'B', value: 0.015 },
  { alloyCode: 'MZ', element: 'CB', value: 1.0 },
  { alloyCode: 'MZ', element: 'HF', value: 2.1 },
  { alloyCode: 'MZ', element: 'NI', value: 59.9 },
  { alloyCode: 'PA', element: 'C', value: 0.11 },
  { alloyCode: 'PA', element: 'CR', value: 11.9 },
  { alloyCode: 'PA', element: 'MO', value: 1.8 },
  { alloyCode: 'PA', element: 'TI', value: 4.0 },
  { alloyCode: 'PA', element: 'AL', value: 3.65 },
  { alloyCode: 'PA', element: 'CO', value: 8.7 },
  { alloyCode: 'PA', element: 'W', value: 3.8 },
  { alloyCode: 'PA', element: 'ZR', value: 0.007 },
  { alloyCode: 'PA', element: 'B', value: 0.013 },
  { alloyCode: 'PA', element: 'TA', value: 5.1 },
  { alloyCode: 'PA', element: 'NI', value: 60.9 },
  { alloyCode: 'PB', element: 'C', value: 0.09 },
  { alloyCode: 'PB', element: 'CR', value: 12.1 },
  { alloyCode: 'PB', element: 'MO', value: 1.9 },
  { alloyCode: 'PB', element: 'TI', value: 4.1 },
  { alloyCode: 'PB', element: 'AL', value: 3.55 },
  { alloyCode: 'PB', element: 'CO', value: 9.0 },
  { alloyCode: 'PB', element: 'W', value: 3.7 },
  { alloyCode: 'PB', element: 'B', value: 0.015 },
  { alloyCode: 'PB', element: 'TA', value: 5.05 },
  { alloyCode: 'PB', element: 'NI', value: 60.5 },
  { alloyCode: 'PD', element: 'C', value: 0.042 },
  { alloyCode: 'PD', element: 'CR', value: 9.8 },
  { alloyCode: 'PD', element: 'TI', value: 1.4 },
  { alloyCode: 'PD', element: 'AL', value: 5.0 },
  { alloyCode: 'PD', element: 'CO', value: 5.4 },
  { alloyCode: 'PD', element: 'W', value: 4.1 },
  { alloyCode: 'PD', element: 'TA', value: 12.0 },
  { alloyCode: 'PD', element: 'NI', value: 62.3 },
  { alloyCode: 'PE', element: 'C', value: 0.61 },
  { alloyCode: 'PE', element: 'CR', value: 23.0 },
  { alloyCode: 'PE', element: 'TI', value: 0.21 },
  { alloyCode: 'PE', element: 'AL', value: 0.21 },
  { alloyCode: 'PE', element: 'CO', value: 55.52 },
  { alloyCode: 'PE', element: 'W', value: 7.0 },
  { alloyCode: 'PE', element: 'TA', value: 3.7 },
  { alloyCode: 'PE', element: 'NI', value: 9.75 },
  { alloyCode: 'PE', element: 'ZR', value: 0.006 },
  { alloyCode: 'PE', element: 'B', value: 0.015 },
  { alloyCode: 'PG', element: 'C', value: 0.06 },
  { alloyCode: 'PG', element: 'CR', value: 21.4 },
  { alloyCode: 'PG', element: 'MO', value: 9.0 },
  { alloyCode: 'PG', element: 'TI', value: 0.3 },
  { alloyCode: 'PG', element: 'AL', value: 0.3 },
  { alloyCode: 'PG', element: 'CB', value: 3.6 },
  { alloyCode: 'PG', element: 'NI', value: 65.34 },
  { alloyCode: 'PH', element: 'C', value: 0.042 },
  { alloyCode: 'PH', element: 'CR', value: 9.8 },
  { alloyCode: 'PH', element: 'TI', value: 1.4 },
  { alloyCode: 'PH', element: 'AL', value: 5.0 },
  { alloyCode: 'PH', element: 'CO', value: 5.4 },
  { alloyCode: 'PH', element: 'W', value: 4.1 },
  { alloyCode: 'PH', element: 'TA', value: 12.0 },
  { alloyCode: 'PH', element: 'HF', value: 0.35 },
  { alloyCode: 'PH', element: 'NI', value: 61.9 },
  { alloyCode: 'PJ', element: 'C', value: 0.12 },
  { alloyCode: 'PJ', element: 'CR', value: 8.9 },
  { alloyCode: 'PJ', element: 'MO', value: 1.8 },
  { alloyCode: 'PJ', element: 'TI', value: 2.5 },
  { alloyCode: 'PJ', element: 'AL', value: 4.75 },
  { alloyCode: 'PJ', element: 'CO', value: 9.8 },
  { alloyCode: 'PJ', element: 'W', value: 6.8 },
  { alloyCode: 'PJ', element: 'ZR', value: 0.035 },
  { alloyCode: 'PJ', element: 'B', value: 0.015 },
  { alloyCode: 'PJ', element: 'TA', value: 3.8 },
  { alloyCode: 'PJ', element: 'HF', value: 1.55 },
  { alloyCode: 'PJ', element: 'NI', value: 59.9 },
  { alloyCode: 'PK', element: 'CR', value: 10.3 },
  { alloyCode: 'PK', element: 'MO', value: 0.9 },
  { alloyCode: 'PK', element: 'TI', value: 3.3 },
  { alloyCode: 'PK', element: 'AL', value: 4.4 },
  { alloyCode: 'PK', element: 'CO', value: 2.5 },
  { alloyCode: 'PK', element: 'W', value: 6.7 },
  { alloyCode: 'PK', element: 'TA', value: 4.8 },
  { alloyCode: 'PK', element: 'NI', value: 67.1 },
  { alloyCode: 'PL', element: 'C', value: 0.15 },
  { alloyCode: 'PL', element: 'CR', value: 22.4 },
  { alloyCode: 'PL', element: 'TI', value: 3.7 },
  { alloyCode: 'PL', element: 'AL', value: 1.9 },
  { alloyCode: 'PL', element: 'CO', value: 19.0 },
  { alloyCode: 'PL', element: 'W', value: 2.0 },
  { alloyCode: 'PL', element: 'ZR', value: 0.025 },
  { alloyCode: 'PL', element: 'B', value: 0.005 },
  { alloyCode: 'PL', element: 'CB', value: 1.0 },
  { alloyCode: 'PL', element: 'TA', value: 1.4 },
  { alloyCode: 'PL', element: 'NI', value: 48.4 },
  { alloyCode: 'PN', element: 'C', value: 0.07 },
  { alloyCode: 'PN', element: 'CR', value: 12.0 },
  { alloyCode: 'PN', element: 'MO', value: 1.9 },
  { alloyCode: 'PN', element: 'TI', value: 4.1 },
  { alloyCode: 'PN', element: 'AL', value: 3.55 },
  { alloyCode: 'PN', element: 'CO', value: 9.0 },
  { alloyCode: 'PN', element: 'W', value: 3.9 },
  { alloyCode: 'PN', element: 'TA', value: 5.0 },
  { alloyCode: 'PN', element: 'NI', value: 60.5 },
  { alloyCode: 'PT', element: 'C', value: 0.08 },
  { alloyCode: 'PT', element: 'CR', value: 12.4 },
  { alloyCode: 'PT', element: 'MO', value: 1.9 },
  { alloyCode: 'PT', element: 'TI', value: 4.1 },
  { alloyCode: 'PT', element: 'AL', value: 3.55 },
  { alloyCode: 'PT', element: 'CO', value: 9.0 },
  { alloyCode: 'PT', element: 'W', value: 4.0 },
  { alloyCode: 'PT', element: 'ZR', value: 0.015 },
  { alloyCode: 'PT', element: 'B', value: 0.015 },
  { alloyCode: 'PT', element: 'TA', value: 4.25 },
  { alloyCode: 'PT', element: 'NI', value: 60.7 },
  { alloyCode: 'PZ', element: 'C', value: 0.11 },
  { alloyCode: 'PZ', element: 'CR', value: 8.15 },
  { alloyCode: 'PZ', element: 'MO', value: 0.5 },
  { alloyCode: 'PZ', element: 'TI', value: 0.7 },
  { alloyCode: 'PZ', element: 'AL', value: 5.6 },
  { alloyCode: 'PZ', element: 'CO', value: 9.25 },
  { alloyCode: 'PZ', element: 'W', value: 9.4 },
  { alloyCode: 'PZ', element: 'ZR', value: 0.015 },
  { alloyCode: 'PZ', element: 'B', value: 0.015 },
  { alloyCode: 'PZ', element: 'TA', value: 3.25 },
  { alloyCode: 'PZ', element: 'HF', value: 1.5 },
  { alloyCode: 'PZ', element: 'NI', value: 61.5 },
  { alloyCode: 'RA', element: 'C', value: 0.026 },
  { alloyCode: 'RA', element: 'CR', value: 6.4 },
  { alloyCode: 'RA', element: 'MO', value: 0.6 },
  { alloyCode: 'RA', element: 'TI', value: 1.0 },
  { alloyCode: 'RA', element: 'AL', value: 5.6 },
  { alloyCode: 'RA', element: 'CO', value: 9.6 },
  { alloyCode: 'RA', element: 'W', value: 6.4 },
  { alloyCode: 'RA', element: 'B', value: 0.007 },
  { alloyCode: 'RA', element: 'TA', value: 6.5 },
  { alloyCode: 'RA', element: 'HF', value: 0.2 },
  { alloyCode: 'RA', element: 'RE', value: 2.9 },
  { alloyCode: 'RA', element: 'NI', value: 60.8 },
  { alloyCode: 'RC', element: 'C', value: 0.04 },
  { alloyCode: 'RC', element: 'CR', value: 6.4 },
  { alloyCode: 'RC', element: 'MO', value: 0.6 },
  { alloyCode: 'RC', element: 'TI', value: 1.0 },
  { alloyCode: 'RC', element: 'AL', value: 5.6 },
  { alloyCode: 'RC', element: 'CO', value: 9.6 },
  { alloyCode: 'RC', element: 'W', value: 6.4 },
  { alloyCode: 'RC', element: 'B', value: 0.007 },
  { alloyCode: 'RC', element: 'TA', value: 6.5 },
  { alloyCode: 'RC', element: 'HF', value: 0.2 },
  { alloyCode: 'RC', element: 'RE', value: 2.9 },
  { alloyCode: 'RC', element: 'NI', value: 60.8 },
  { alloyCode: 'RD', element: 'C', value: 0.12 },
  { alloyCode: 'RD', element: 'CR', value: 6.85 },
  { alloyCode: 'RD', element: 'MO', value: 1.5 },
  { alloyCode: 'RD', element: 'AL', value: 6.0 },
  { alloyCode: 'RD', element: 'CO', value: 11.75 },
  { alloyCode: 'RD', element: 'W', value: 4.8 },
  { alloyCode: 'RD', element: 'B', value: 0.015 },
  { alloyCode: 'RD', element: 'TA', value: 6.35 },
  { alloyCode: 'RD', element: 'HF', value: 1.6 },
  { alloyCode: 'RD', element: 'RE', value: 2.7 },
  { alloyCode: 'RD', element: 'NI', value: 58.3 },
  { alloyCode: 'RE', element: 'C', value: 0.059 },
  { alloyCode: 'RE', element: 'CR', value: 7.15 },
  { alloyCode: 'RE', element: 'MO', value: 1.45 },
  { alloyCode: 'RE', element: 'AL', value: 6.15 },
  { alloyCode: 'RE', element: 'CO', value: 7.5 },
  { alloyCode: 'RE', element: 'W', value: 4.9 },
  { alloyCode: 'RE', element: 'B', value: 0.004 },
  { alloyCode: 'RE', element: 'TA', value: 6.45 },
  { alloyCode: 'RE', element: 'HF', value: 0.15 },
  { alloyCode: 'RE', element: 'RE', value: 2.9 },
  { alloyCode: 'RE', element: 'NI', value: 63.3 },
  { alloyCode: 'RG', element: 'C', value: 0.11 },
  { alloyCode: 'RG', element: 'CR', value: 6.55 },
  { alloyCode: 'RG', element: 'MO', value: 1.7 },
  { alloyCode: 'RG', element: 'AL', value: 6.05 },
  { alloyCode: 'RG', element: 'CO', value: 12.45 },
  { alloyCode: 'RG', element: 'W', value: 6.45 },
  { alloyCode: 'RG', element: 'ZR', value: 0.05 },
  { alloyCode: 'RG', element: 'B', value: 0.013 },
  { alloyCode: 'RG', element: 'TA', value: 4.05 },
  { alloyCode: 'RG', element: 'HF', value: 1.55 },
  { alloyCode: 'RG', element: 'RE', value: 3.0 },
  { alloyCode: 'RG', element: 'NI', value: 58.0 },
  { alloyCode: 'RH', element: 'C', value: 0.023 },
  { alloyCode: 'RH', element: 'CR', value: 4.9 },
  { alloyCode: 'RH', element: 'MO', value: 1.9 },
  { alloyCode: 'RH', element: 'AL', value: 5.65 },
  { alloyCode: 'RH', element: 'CO', value: 10.0 },
  { alloyCode: 'RH', element: 'W', value: 5.9 },
  { alloyCode: 'RH', element: 'TA', value: 8.6 },
  { alloyCode: 'RH', element: 'HF', value: 0.35 },
  { alloyCode: 'RH', element: 'RE', value: 3.0 },
  { alloyCode: 'RH', element: 'NI', value: 59.7 },
  { alloyCode: 'RJ', element: 'C', value: 0.05 },
  { alloyCode: 'RJ', element: 'CR', value: 4.5 },
  { alloyCode: 'RJ', element: 'AL', value: 6.3 },
  { alloyCode: 'RJ', element: 'CO', value: 12.5 },
  { alloyCode: 'RJ', element: 'W', value: 5.75 },
  { alloyCode: 'RJ', element: 'B', value: 0.004 },
  { alloyCode: 'RJ', element: 'TA', value: 7.0 },
  { alloyCode: 'RJ', element: 'HF', value: 0.16 },
  { alloyCode: 'RJ', element: 'RE', value: 6.25 },
  { alloyCode: 'RJ', element: 'NI', value: 57.5 },
  { alloyCode: 'RK', element: 'CR', value: 6.5 },
  { alloyCode: 'RK', element: 'MO', value: 0.6 },
  { alloyCode: 'RK', element: 'TI', value: 1.0 },
  { alloyCode: 'RK', element: 'AL', value: 5.6 },
  { alloyCode: 'RK', element: 'CO', value: 9.6 },
  { alloyCode: 'RK', element: 'W', value: 6.4 },
  { alloyCode: 'RK', element: 'TA', value: 6.5 },
  { alloyCode: 'RK', element: 'HF', value: 0.09 },
  { alloyCode: 'RK', element: 'RE', value: 2.9 },
  { alloyCode: 'RK', element: 'NI', value: 60.8 },
  { alloyCode: 'RL', element: 'CR', value: 6.0 },
  { alloyCode: 'RL', element: 'MO', value: 0.5 },
  { alloyCode: 'RL', element: 'TI', value: 0.7 },
  { alloyCode: 'RL', element: 'AL', value: 5.7 },
  { alloyCode: 'RL', element: 'CO', value: 9.25 },
  { alloyCode: 'RL', element: 'W', value: 8.5 },
  { alloyCode: 'RL', element: 'ZR', value: 0.007 },
  { alloyCode: 'RL', element: 'B', value: 0.016 },
  { alloyCode: 'RL', element: 'TA', value: 3.4 },
  { alloyCode: 'RL', element: 'HF', value: 1.4 },
  { alloyCode: 'RL', element: 'RE', value: 2.95 },
  { alloyCode: 'RL', element: 'NI', value: 61.6 },
  { alloyCode: 'RN', element: 'C', value: 0.04 },
  { alloyCode: 'RN', element: 'SI', value: 0.04 },
  { alloyCode: 'RN', element: 'CR', value: 13.1 },
  { alloyCode: 'RN', element: 'AL', value: 6.6 },
  { alloyCode: 'RN', element: 'CO', value: 7.25 },
  { alloyCode: 'RN', element: 'W', value: 3.75 },
  { alloyCode: 'RN', element: 'B', value: 0.004 },
  { alloyCode: 'RN', element: 'TA', value: 4.95 },
  { alloyCode: 'RN', element: 'HF', value: 0.15 },
  { alloyCode: 'RN', element: 'RE', value: 1.45 },
  { alloyCode: 'RN', element: 'NI', value: 62.7 },
  { alloyCode: 'RS', element: 'C', value: 0.0575 },
  { alloyCode: 'RS', element: 'CR', value: 7.15 },
  { alloyCode: 'RS', element: 'MO', value: 1.45 },
  { alloyCode: 'RS', element: 'AL', value: 6.1 },
  { alloyCode: 'RS', element: 'CO', value: 7.5 },
  { alloyCode: 'RS', element: 'W', value: 4.9 },
  { alloyCode: 'RS', element: 'B', value: 0.004 },
  { alloyCode: 'RS', element: 'TA', value: 6.5 },
  { alloyCode: 'RS', element: 'HF', value: 0.15 },
  { alloyCode: 'RS', element: 'RE', value: 2.9 },
  { alloyCode: 'RS', element: 'NI', value: 63.3 },
  { alloyCode: 'RT', element: 'C', value: 0.037 },
  { alloyCode: 'RT', element: 'CR', value: 6.0 },
  { alloyCode: 'RT', element: 'MO', value: 2.0 },
  { alloyCode: 'RT', element: 'AL', value: 6.3 },
  { alloyCode: 'RT', element: 'CO', value: 7.5 },
  { alloyCode: 'RT', element: 'W', value: 6.25 },
  { alloyCode: 'RT', element: 'B', value: 0.004 },
  { alloyCode: 'RT', element: 'TA', value: 6.5 },
  { alloyCode: 'RT', element: 'HF', value: 0.6 },
  { alloyCode: 'RT', element: 'RE', value: 1.4 },
  { alloyCode: 'RT', element: 'NI', value: 63.4 },
  { alloyCode: 'RU', element: 'C', value: 0.0225 },
  { alloyCode: 'RU', element: 'CR', value: 4.9 },
  { alloyCode: 'RU', element: 'MO', value: 1.9 },
  { alloyCode: 'RU', element: 'AL', value: 5.65 },
  { alloyCode: 'RU', element: 'CO', value: 10.0 },
  { alloyCode: 'RU', element: 'W', value: 5.9 },
  { alloyCode: 'RU', element: 'TA', value: 8.6 },
  { alloyCode: 'RU', element: 'HF', value: 0.1 },
  { alloyCode: 'RU', element: 'RE', value: 3.0 },
  { alloyCode: 'RU', element: 'NI', value: 59.9 },
  { alloyCode: 'SB', element: 'C', value: 0.17 },
  { alloyCode: 'SB', element: 'CR', value: 13.9 },
  { alloyCode: 'SB', element: 'MO', value: 4.05 },
  { alloyCode: 'SB', element: 'TI', value: 4.85 },
  { alloyCode: 'SB', element: 'AL', value: 3.0 },
  { alloyCode: 'SB', element: 'CO', value: 9.35 },
  { alloyCode: 'SB', element: 'W', value: 4.05 },
  { alloyCode: 'SB', element: 'ZR', value: 0.012 },
  { alloyCode: 'SB', element: 'B', value: 0.014 },
  { alloyCode: 'SB', element: 'HF', value: 0.8 },
  { alloyCode: 'SB', element: 'NI', value: 59.8 },
  { alloyCode: 'SE', element: 'C', value: 0.08 },
  { alloyCode: 'SE', element: 'CR', value: 15.0 },
  { alloyCode: 'SE', element: 'MO', value: 4.4 },
  { alloyCode: 'SE', element: 'TI', value: 2.35 },
  { alloyCode: 'SE', element: 'AL', value: 4.35 },
  { alloyCode: 'SE', element: 'CO', value: 22.0 },
  { alloyCode: 'SE', element: 'B', value: 0.015 },
  { alloyCode: 'SE', element: 'NI', value: 51.8 },
  { alloyCode: 'SR', element: 'CR', value: 5.3 },
  { alloyCode: 'SR', element: 'MO', value: 1.7 },
  { alloyCode: 'SR', element: 'TI', value: 1.0 },
  { alloyCode: 'SR', element: 'AL', value: 5.2 },
  { alloyCode: 'SR', element: 'CO', value: 10.0 },
  { alloyCode: 'SR', element: 'W', value: 5.0 },
  { alloyCode: 'SR', element: 'TA', value: 8.8 },
  { alloyCode: 'SR', element: 'HF', value: 0.1 },
  { alloyCode: 'SR', element: 'RE', value: 3.0 },
  { alloyCode: 'SR', element: 'NI', value: 59.9 },
  { alloyCode: 'TA', element: 'C', value: 0.13 },
  { alloyCode: 'TA', element: 'CR', value: 13.8 },
  { alloyCode: 'TA', element: 'MO', value: 4.0 },
  { alloyCode: 'TA', element: 'TI', value: 0.9 },
  { alloyCode: 'TA', element: 'AL', value: 6.0 },
  { alloyCode: 'TA', element: 'ZR', value: 0.065 },
  { alloyCode: 'TA', element: 'B', value: 0.01 },
  { alloyCode: 'TA', element: 'CB', value: 1.9 },
  { alloyCode: 'TA', element: 'NI', value: 73.2 },
  { alloyCode: 'TB', element: 'C', value: 0.095 },
  { alloyCode: 'TB', element: 'CR', value: 8.4 },
  { alloyCode: 'TB', element: 'MO', value: 0.5 },
  { alloyCode: 'TB', element: 'TI', value: 0.75 },
  { alloyCode: 'TB', element: 'AL', value: 5.5 },
  { alloyCode: 'TB', element: 'CO', value: 9.5 },
  { alloyCode: 'TB', element: 'W', value: 9.5 },
  { alloyCode: 'TB', element: 'ZR', value: 0.015 },
  { alloyCode: 'TB', element: 'B', value: 0.015 },
  { alloyCode: 'TB', element: 'TA', value: 3.0 },
  { alloyCode: 'TB', element: 'HF', value: 1.6 },
  { alloyCode: 'TB', element: 'NI', value: 61.1 },
  { alloyCode: 'TG', element: 'C', value: 0.16 },
  { alloyCode: 'TG', element: 'CR', value: 8.25 },
  { alloyCode: 'TG', element: 'MO', value: 0.75 },
  { alloyCode: 'TG', element: 'TI', value: 1.0 },
  { alloyCode: 'TG', element: 'AL', value: 5.55 },
  { alloyCode: 'TG', element: 'CO', value: 9.9 },
  { alloyCode: 'TG', element: 'W', value: 10.05 },
  { alloyCode: 'TG', element: 'ZR', value: 0.032 },
  { alloyCode: 'TG', element: 'B', value: 0.015 },
  { alloyCode: 'TG', element: 'TA', value: 3.0 },
  { alloyCode: 'TG', element: 'HF', value: 1.5 },
  { alloyCode: 'TG', element: 'NI', value: 59.8 },
  { alloyCode: 'TH', element: 'C', value: 0.11 },
  { alloyCode: 'TH', element: 'CR', value: 16.0 },
  { alloyCode: 'TH', element: 'MO', value: 1.85 },
  { alloyCode: 'TH', element: 'TI', value: 3.35 },
  { alloyCode: 'TH', element: 'AL', value: 3.35 },
  { alloyCode: 'TH', element: 'CO', value: 8.25 },
  { alloyCode: 'TH', element: 'W', value: 2.5 },
  { alloyCode: 'TH', element: 'ZR', value: 0.025 },
  { alloyCode: 'TH', element: 'B', value: 0.009 },
  { alloyCode: 'TH', element: 'CB', value: 0.9 },
  { alloyCode: 'TH', element: 'TA', value: 1.75 },
  { alloyCode: 'TH', element: 'NI', value: 61.9 },
  { alloyCode: 'TJ', element: 'C', value: 0.08 },
  { alloyCode: 'TJ', element: 'CR', value: 12.7 },
  { alloyCode: 'TJ', element: 'MO', value: 1.95 },
  { alloyCode: 'TJ', element: 'TI', value: 4.05 },
  { alloyCode: 'TJ', element: 'AL', value: 3.4 },
  { alloyCode: 'TJ', element: 'CO', value: 8.9 },
  { alloyCode: 'TJ', element: 'W', value: 4.05 },
  { alloyCode: 'TJ', element: 'ZR', value: 0.033 },
  { alloyCode: 'TJ', element: 'B', value: 0.015 },
  { alloyCode: 'TJ', element: 'TA', value: 4.3 },
  { alloyCode: 'TJ', element: 'HF', value: 0.95 },
  { alloyCode: 'TJ', element: 'NI', value: 59.6 },
  { alloyCode: 'TL', element: 'C', value: 0.09 },
  { alloyCode: 'TL', element: 'CR', value: 14.0 },
  { alloyCode: 'TL', element: 'MO', value: 1.5 },
  { alloyCode: 'TL', element: 'TI', value: 4.9 },
  { alloyCode: 'TL', element: 'AL', value: 3.0 },
  { alloyCode: 'TL', element: 'CO', value: 9.35 },
  { alloyCode: 'TL', element: 'W', value: 3.8 },
  { alloyCode: 'TL', element: 'B', value: 0.012 },
  { alloyCode: 'TL', element: 'CB', value: 0.12 },
  { alloyCode: 'TL', element: 'TA', value: 2.55 },
  { alloyCode: 'TL', element: 'NI', value: 60.7 },
  { alloyCode: 'TM', element: 'C', value: 0.072 },
  { alloyCode: 'TM', element: 'CR', value: 8.12 },
  { alloyCode: 'TM', element: 'MO', value: 0.53 },
  { alloyCode: 'TM', element: 'TI', value: 0.73 },
  { alloyCode: 'TM', element: 'AL', value: 5.6 },
  { alloyCode: 'TM', element: 'CO', value: 9.35 },
  { alloyCode: 'TM', element: 'W', value: 9.45 },
  { alloyCode: 'TM', element: 'ZR', value: 0.01 },
  { alloyCode: 'TM', element: 'B', value: 0.016 },
  { alloyCode: 'TM', element: 'TA', value: 3.23 },
  { alloyCode: 'TM', element: 'HF', value: 1.5 },
  { alloyCode: 'TM', element: 'NI', value: 61.4 },
  { alloyCode: 'TO', element: 'C', value: 0.09 },
  { alloyCode: 'TO', element: 'CR', value: 14.0 },
  { alloyCode: 'TO', element: 'MO', value: 1.5 },
  { alloyCode: 'TO', element: 'TI', value: 4.8 },
  { alloyCode: 'TO', element: 'AL', value: 2.87 },
  { alloyCode: 'TO', element: 'CO', value: 9.35 },
  { alloyCode: 'TO', element: 'W', value: 3.8 },
  { alloyCode: 'TO', element: 'ZR', value: 0.007 },
  { alloyCode: 'TO', element: 'B', value: 0.012 },
  { alloyCode: 'TO', element: 'TA', value: 2.55 },
  { alloyCode: 'TO', element: 'NI', value: 60.7 },
  { alloyCode: 'TP', element: 'C', value: 0.105 },
  { alloyCode: 'TP', element: 'CR', value: 8.9 },
  { alloyCode: 'TP', element: 'MO', value: 1.8 },
  { alloyCode: 'TP', element: 'TI', value: 2.4 },
  { alloyCode: 'TP', element: 'AL', value: 4.75 },
  { alloyCode: 'TP', element: 'CO', value: 9.8 },
  { alloyCode: 'TP', element: 'W', value: 6.9 },
  { alloyCode: 'TP', element: 'ZR', value: 0.035 },
  { alloyCode: 'TP', element: 'B', value: 0.015 },
  { alloyCode: 'TP', element: 'TA', value: 3.7 },
  { alloyCode: 'TP', element: 'HF', value: 1.55 },
  { alloyCode: 'TP', element: 'NI', value: 60.0 },
  { alloyCode: 'TR', element: 'C', value: 0.105 },
  { alloyCode: 'TR', element: 'CR', value: 8.9 },
  { alloyCode: 'TR', element: 'MO', value: 1.8 },
  { alloyCode: 'TR', element: 'TI', value: 2.4 },
  { alloyCode: 'TR', element: 'AL', value: 4.75 },
  { alloyCode: 'TR', element: 'CO', value: 9.8 },
  { alloyCode: 'TR', element: 'W', value: 6.9 },
  { alloyCode: 'TR', element: 'ZR', value: 0.035 },
  { alloyCode: 'TR', element: 'B', value: 0.015 },
  { alloyCode: 'TR', element: 'TA', value: 3.7 },
  { alloyCode: 'TR', element: 'HF', value: 1.55 },
  { alloyCode: 'TR', element: 'NI', value: 60.0 },
  { alloyCode: 'TV', element: 'C', value: 0.11 },
  { alloyCode: 'TV', element: 'CR', value: 16.0 },
  { alloyCode: 'TV', element: 'MO', value: 1.75 },
  { alloyCode: 'TV', element: 'TI', value: 3.45 },
  { alloyCode: 'TV', element: 'AL', value: 3.3 },
  { alloyCode: 'TV', element: 'CO', value: 8.5 },
  { alloyCode: 'TV', element: 'W', value: 2.6 },
  { alloyCode: 'TV', element: 'ZR', value: 0.032 },
  { alloyCode: 'TV', element: 'B', value: 0.009 },
  { alloyCode: 'TV', element: 'CB', value: 0.9 },
  { alloyCode: 'TV', element: 'TA', value: 1.75 },
  { alloyCode: 'TV', element: 'NI', value: 61.6 },
  { alloyCode: 'VA', element: 'C', value: 0.11 },
  { alloyCode: 'VA', element: 'CR', value: 16.0 },
  { alloyCode: 'VA', element: 'MO', value: 1.7 },
  { alloyCode: 'VA', element: 'TI', value: 3.4 },
  { alloyCode: 'VA', element: 'AL', value: 3.3 },
  { alloyCode: 'VA', element: 'CO', value: 8.3 },
  { alloyCode: 'VA', element: 'W', value: 2.6 },
  { alloyCode: 'VA', element: 'ZR', value: 0.033 },
  { alloyCode: 'VA', element: 'B', value: 0.009 },
  { alloyCode: 'VA', element: 'CB', value: 1.7 },
  { alloyCode: 'VA', element: 'NI', value: 62.8 },
  { alloyCode: 'VE', element: 'C', value: 0.062 },
  { alloyCode: 'VE', element: 'CR', value: 9.75 },
  { alloyCode: 'VE', element: 'MO', value: 1.48 },
  { alloyCode: 'VE', element: 'TI', value: 3.45 },
  { alloyCode: 'VE', element: 'AL', value: 4.18 },
  { alloyCode: 'VE', element: 'CO', value: 7.38 },
  { alloyCode: 'VE', element: 'W', value: 5.9 },
  { alloyCode: 'VE', element: 'B', value: 0.0037 },
  { alloyCode: 'VE', element: 'CB', value: 0.48 },
  { alloyCode: 'VE', element: 'TA', value: 4.7 },
  { alloyCode: 'VE', element: 'HF', value: 0.13 },
  { alloyCode: 'VE', element: 'NI', value: 62.5 },
  { alloyCode: 'VF', element: 'C', value: 0.03 },
  { alloyCode: 'VF', element: 'CR', value: 19.0 },
  { alloyCode: 'VF', element: 'MO', value: 3.2 },
  { alloyCode: 'VF', element: 'TI', value: 1.0 },
  { alloyCode: 'VF', element: 'AL', value: 0.5 },
  { alloyCode: 'VF', element: 'CO', value: 12.0 },
  { alloyCode: 'VF', element: 'B', value: 0.004 },
  { alloyCode: 'VF', element: 'CB', value: 5.15 },
  { alloyCode: 'VF', element: 'TA', value: 3.25 },
  { alloyCode: 'VF', element: 'NI', value: 55.9 },
  { alloyCode: 'VS', element: 'C', value: 0.06 },
  { alloyCode: 'VS', element: 'CR', value: 9.7 },
  { alloyCode: 'VS', element: 'MO', value: 1.44 },
  { alloyCode: 'VS', element: 'TI', value: 3.45 },
  { alloyCode: 'VS', element: 'AL', value: 4.18 },
  { alloyCode: 'VS', element: 'CO', value: 7.38 },
  { alloyCode: 'VS', element: 'W', value: 5.9 },
  { alloyCode: 'VS', element: 'B', value: 0.0037 },
  { alloyCode: 'VS', element: 'CB', value: 0.48 },
  { alloyCode: 'VS', element: 'TA', value: 4.7 },
  { alloyCode: 'VS', element: 'HF', value: 0.13 },
  { alloyCode: 'VS', element: 'NI', value: 62.6 },
  { alloyCode: 'VT', element: 'C', value: 0.094 },
  { alloyCode: 'VT', element: 'CR', value: 15.85 },
  { alloyCode: 'VT', element: 'MO', value: 1.6 },
  { alloyCode: 'VT', element: 'TI', value: 3.3 },
  { alloyCode: 'VT', element: 'AL', value: 3.53 },
  { alloyCode: 'VT', element: 'CO', value: 8.15 },
  { alloyCode: 'VT', element: 'W', value: 2.55 },
  { alloyCode: 'VT', element: 'ZR', value: 0.019 },
  { alloyCode: 'VT', element: 'B', value: 0.015 },
  { alloyCode: 'VT', element: 'CB', value: 0.78 },
  { alloyCode: 'VT', element: 'TA', value: 1.66 },
  { alloyCode: 'VT', element: 'NI', value: 62.5 },
  { alloyCode: 'WR', element: 'C', value: 0.04 },
  { alloyCode: 'WR', element: 'CR', value: 4.0 },
  { alloyCode: 'WR', element: 'MO', value: 2.0 },
  { alloyCode: 'WR', element: 'AL', value: 5.9 },
  { alloyCode: 'WR', element: 'CO', value: 12.5 },
  { alloyCode: 'WR', element: 'W', value: 9.0 },
  { alloyCode: 'WR', element: 'TA', value: 8.9 },
  { alloyCode: 'WR', element: 'HF', value: 0.35 },
  { alloyCode: 'WR', element: 'NI', value: 57.3 },
];

const revenue = [
  { month: 'Jan', revenue: 2000 },
  { month: 'Feb', revenue: 1800 },
  { month: 'Mar', revenue: 2200 },
  { month: 'Apr', revenue: 2500 },
  { month: 'May', revenue: 2300 },
  { month: 'Jun', revenue: 3200 },
  { month: 'Jul', revenue: 3500 },
  { month: 'Aug', revenue: 3700 },
  { month: 'Sep', revenue: 2500 },
  { month: 'Oct', revenue: 2800 },
  { month: 'Nov', revenue: 3000 },
  { month: 'Dec', revenue: 4800 },
];

export { users, alloys, alloyChemistries, revenue };
